// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKa2s7mmnpBUMbCEUWdpoDMeOD3grnnY',
    appId: '1:175690916181:web:ab58b7b0d5b2c558c8cfdc',
    messagingSenderId: '175690916181',
    projectId: 'my-todo-950ee',
    authDomain: 'my-todo-950ee.firebaseapp.com',
    storageBucket: 'my-todo-950ee.appspot.com',
    measurementId: 'G-X71NWG0P21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilpP8FodnZeuTiRrO0yuGY8gF_ERzdSE',
    appId: '1:175690916181:android:ea7b6ede97359b02c8cfdc',
    messagingSenderId: '175690916181',
    projectId: 'my-todo-950ee',
    storageBucket: 'my-todo-950ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8VYvh_45nnEEhTxE6222fdIbpv9b5UT0',
    appId: '1:175690916181:ios:30e266bf7db6d548c8cfdc',
    messagingSenderId: '175690916181',
    projectId: 'my-todo-950ee',
    storageBucket: 'my-todo-950ee.appspot.com',
    iosBundleId: 'com.example.iHaveTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8VYvh_45nnEEhTxE6222fdIbpv9b5UT0',
    appId: '1:175690916181:ios:30e266bf7db6d548c8cfdc',
    messagingSenderId: '175690916181',
    projectId: 'my-todo-950ee',
    storageBucket: 'my-todo-950ee.appspot.com',
    iosBundleId: 'com.example.iHaveTodo',
  );
}
